name: Build macOS PKG

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download macOS FFmpeg
        run: |
          mkdir -p SilenceCutterAE/client/ffmpeg
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-118837-g7198a27a05.zip -o ffmpeg.zip
          unzip ffmpeg.zip -d SilenceCutterAE/client/ffmpeg/
          chmod +x SilenceCutterAE/client/ffmpeg/ffmpeg

      - name: Install Node Dependencies
        run: |
          if [ -d "SilenceCutterAE/client" ]; then
            cd SilenceCutterAE/client
            npm install
          fi

      - name: Make script executable
        run: chmod +x build_mac_pkg.sh

      - name: Run Mac Package Script
        run: ./build_mac_pkg.sh

      - name: Upload PKG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SilenceCutter-Mac-Installer
          path: "*.pkg"
